spring.application.name=auction

server.port=8083

spring.datasource.url=jdbc:sqlite:./data/auction.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

services.catalogueBaseUrl=http://localhost:8082
