spring.application.name=iam

server.port=8081

# services.iamBaseUrl=http://localhost:8081

spring.datasource.url=jdbc:sqlite:./data/iam.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
