spring.application.name=catalogue

server.port=8082

# services.catalogueBaseUrl=http://localhost:8082

spring.datasource.url=jdbc:sqlite:./data/catalogue.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# spring.datasource.username=
# spring.datasource.password=
spring.sql.init.mode=always
